# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6319e7b62fe838ea223c00ebcee005ee55f2ccdc22f9eabf6163cce8163261c04851fbb713a34d3f2645417d0629af4f8de4e160b11c340462822ddda6e01b1

test:
  secret_key_base: f8fad58b36754cfee9be860434896e389cd260ee574198d7a85dbcbac631ff44905b91de89c2827042100e06aee0c7fc8b60ba75c0afeb6673ba77aed5862125

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
